### ISSUE TITLE
(feature request) several env would be nice in rc file 

### ISSUE THREAD

**Issue by laurentorban** [mahlonsmith/shelldap#1]
something like this :

cat ~/.shelldap.rc

server: ldap.inet.com
binddn: cn=read-only-admin,dc=example,dc=com
bindpass: password
basedn: dc=example,dc=com

vm:
server: 192.168.1.10
binddn: cn=admin,dc=support,dc=com
bindpass: mypass
basedn: dc=support,dc=com

the use it like this :
shelldap vm

**Comment by mahlonsmith** [comment]
You can accomplish this by storing your config in separate files, and just use the -f flag to switch between them.

**Comment by mahlonsmith** [comment]
Closing this, as the idea can be accomplished outside of shelldap via separate configs and shell aliasing.
