### ISSUE TITLE
sometimes falls back to simple auth when it should do sasl

### ISSUE THREAD

**Issue by carnil** [mahlonsmith/shelldap#2]
Hi

In Debian downstream the following issue was reported with shelldap, full quoting below:

https://bugs.debian.org/941411

```
Package: shelldap
Version: 1.4.0-4
Severity: normal

Hello,

when calling shelldap repeatedly it sometimes fails for me and sometimes
succeeds in entering the shell:

	user@host:~# shelldap
	LDAP bind error: No password, did you mean noauth or anonymous ?
	user@host:~# shelldap
	~ >

The problem is that in /usr/share/perl5/Net/LDAP.pm in the bind() method
the iteration through %ptype happens in different orderings. If

	password => simple

is hit first it dies with the above error message. If however 

	sasl => sasl

is tried first, it succeeds.

The following patch makes it work for me:

diff --git a/shelldap b/shelldap
index 68dde20cc8de..5a18f23799f0 100755
--- a/shelldap
+++ b/shelldap
@@ -770,7 +770,6 @@ You may try connecting insecurely, or install the module and try again.\n} if $@
 	#
 	if ( $sasl_conn ) {
 		$rv = $ldap->bind( $conf->{'binddn'},
-			password => $conf->{'bindpass'},
 			sasl     => $sasl_conn
 		);
 	}

I *think* you never need a password when using sasl, but I'm not 100%
confident, so I'm not tagging with "patch". I didn't try with shelldap
1.5.0-2 from sid, but there also both sasl and password are passed, so I
expect the problem to still exist there.

Best regards
Uwe
```

**Comment by mahlonsmith** [comment]
Hey Carnil!  Thanks for the relay.  I confess I don't use SASL myself, so I'll need to do some research to find the right solution.  This may be it, but I don't know if that's still true in the PLAIN mechanism case.

Reaching out to the original reporter and try to get some additional information (what his mechanism is, enabling debug, etc.)

**Comment by carnil** [comment]
Hi,

On Mon, Sep 30, 2019 at 09:01:14AM -0700, Mahlon E. Smith wrote:
> Hey Carnil!  Thanks for the relay.  I confess I don't use SASL
> myself, so I'll need to do some research to find the right solution.
> This may be it, but I don't know if that's still true in the PLAIN
> mechanism case.

Thanks for the quick followup. I'm similarly unsure here if this is
the right solution. Regarding the PLAIN mechanism, Net::LDAP::Security
at least mentions:

https://metacpan.org/pod/Net::LDAP::Security

> Net::LDAP supports SASL using the Authen::SASL class. Currently the
> only Authen::SASL subclasses (i.e., SASL mechanism) available are
> CRAM-MD5 and EXTERNAL.

> Reaching out to the original reporter and try to get some additional
> information (what his mechanism is, enabling debug, etc.)

Will you followup with question directly on the Debian bug or should I
try to redirect Uwe here? In case of the former, just mail as well
941411@bugs.debian.org .

Regards,
Salvatore

**Comment by ukleinek** [comment]
In my installation of `Authen::SASL` there is a PLAIN module, but this doesn't seem to use `password` but `pass`. (And this has to be passed in the SASLOBJ not as parameter to `bind()`.)

**Comment by mahlonsmith** [comment]
It seems this patch is valid in the GSSAPI case, but password secrets still have to be known locally in the DIGEST-MD5 case, at least.  (Though the reporter Uwe is correct in that the location of that is elsewhere altogether -- I don't think DIGEST-MD5 ever worked because of this.)

I'm -hoping- @ukleinek is using GSSAPI - I can get DIGEST-MD5 working when sending an explicit sasl user here, if it correctly ignores those values when using GSSAPI, I think that's sufficient to push.

I've added a "sasl-fix" branch for testing.

**Comment by rschwebel** [comment]
On Sat, Oct 05, 2019 at 07:55:05PM -0700, Mahlon E. Smith wrote:
> It seems this patch is valid in the GSSAPI case, but password secrets still
> have to be known locally in the DIGEST-MD5 case, at least. (Though the reporter
> Uwe is correct in that the location of that is elsewhere altogether -- I don't
> think DIGEST-MD5 ever worked because of this.)
> 
> I'm -hoping- Uwe is using GSSAPI - I can get DIGEST-MD5 working when sending an
> explicit sasl user here, if it correctly ignores those values when using
> GSSAPI, I think that's sufficient to push.
> 
> I've added a "sasl-fix" branch for testing.

In our original testcase, we are using EXTERNAL, so Uwe is not using
GSSAPI in this case.

rsc
-- 
Pengutronix e.K.                           | Dipl.-Ing. Robert Schwebel  |
Industrial Linux Solutions                 | https://www.pengutronix.de/ |
Peiner Str. 6-8, 31137 Hildesheim, Germany | Phone: +49-5121-206917-0    |
Amtsgericht Hildesheim, HRA 2686           | Fax:   +49-5121-206917-5555 |

**Comment by mahlonsmith** [comment]
> In our original testcase, we are using EXTERNAL, so Uwe is not using
> GSSAPI in this case.

Gotcha.  In this case, I think the same applies -- hoping by fixing DIGEST-MD5 it doesn't break other mechanisms.  Can you try the patch in the sasl-fix branch and provide feedback for your environment?  (It contains the password removal, just adds fixes for digest-md5.)

**Comment by mahlonsmith** [comment]
Fixed in master.
