### ISSUE TITLE
Cannot delete last attribute

### ISSUE THREAD

**Issue by Shirkanesi** [mahlonsmith/shelldap#9]
Hey,

I've noticed there is still some issue that feels like https://github.com/mahlonsmith/shelldap/issues/4

I cannot delete the last attribute in the ldif. (The last one before the commented lines).

For example:
```ldif
dn: cn=test,ou=groups,dc=example,dc=com
objectClass: groupOfNames
objectClass: klGroup
cn: test
member:
protectedGroup: TRUE
```
When I delete here `protectedGroup` I get `No attributes to update`.

However, in this case
```ldif
dn: cn=test,ou=groups,dc=example,dc=com
objectClass: groupOfNames
objectClass: klGroup
cn: test
member:
protectedGroup: TRUE
requiresProtectedAccount: TRUE
```
I can delete `protectedGroup` but not `requiresProtectedAccount`.

The attributes should have a proper equality-matcher as far as I understand.
```
olcAttributeTypes: {5}( klAttrs:6 NAME 'protectedGroup' DESC 'When true group is protected from automation' EQUALITY booleanMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.7 SINGLE-VALUE)
olcAttributeTypes: {8}( klAttrs:9 NAME 'requiresProtectedAccount' DESC 'When true group requires user to have a protected account' EQUALITY booleanMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.7 SINGLE-VALUE)
```

```
root@infra:~# shelldap --version
shelldap 1.5.1
```

If you need any more information, feel free to ask :D

P.S: I really love shelldap and this one issue where deleting attributes fails from time to time is the only reason I cannot use it full-time :/

**Comment by Shirkanesi** [comment]
Ughh. Never mind. The latest version on master works for me. Any chance you could create a new release so it will actually become part of distro-packages? :D

**Comment by mahlonsmith** [comment]
All set!   :+1:
